INSERT INTO `javainfo`.`emprendimiento`
(`id`,
`activo`,
`contador_de_votos`,
`contenido`,
`descripcion`,
`fecha_de_creacion`,
`nombre`,
`objetivo`,
`publicado`,
`ultima_modificacion`,
`url`,
`jefe_id`)
VALUES
(1,
true,
3,
"Arte y Pintura",
"Cuadros pintados al óleo y con otras técnicas modernas",
"2019-08-02",
"Pinceladas",
50000.00,
true,
"2019-08-14",
"emprendimientos/pincelada",
8);

INSERT INTO `javainfo`.`emprendimiento`
(`id`,
`activo`,
`contador_de_votos`,
`contenido`,
`descripcion`,
`fecha_de_creacion`,
`nombre`,
`objetivo`,
`publicado`,
`ultima_modificacion`,
`url`,
`jefe_id`)
VALUES
(2,
true,
10,
"Programación",
"Aplicaciones sensillas que ayudar a mejorar tu emprendimiento",
"2020-02-02",
"Controllers",
50000.00,
true,
"2020-10-14",
"emprendimientos/Controllers",
1);

INSERT INTO `javainfo`.`emprendimiento`
(`id`,
`activo`,
`contador_de_votos`,
`contenido`,
`descripcion`,
`fecha_de_creacion`,
`nombre`,
`objetivo`,
`publicado`,
`ultima_modificacion`,
`url`,
`jefe_id`)
VALUES
(3,
true,
2,
"Comida",
"Las mejores ensaladas %100 naturales",
"2015-05-02",
"Saludables",
50000.00,
true,
"2019-01-04",
"emprendimientos/ComidaSalud",
2);

INSERT INTO `javainfo`.`emprendimiento`
(`id`,
`activo`,
`contador_de_votos`,
`contenido`,
`descripcion`,
`fecha_de_creacion`,
`nombre`,
`objetivo`,
`publicado`,
`ultima_modificacion`,
`url`,
`jefe_id`)
VALUES
(4,
true,
15,
"Artesanías",
"Las mejores artesanías en la mejor madera...",
"2005-03-09",
"El Norteño",
50000.00,
true,
"2014-10-28",
"emprendimientos/artesanias_norteño",
10);

INSERT INTO `javainfo`.`emprendimiento`
(`id`,
`activo`,
`contador_de_votos`,
`contenido`,
`descripcion`,
`fecha_de_creacion`,
`nombre`,
`objetivo`,
`publicado`,
`ultima_modificacion`,
`url`,
`jefe_id`)
VALUES
(5,
true,
9,
"Tejidos",
"Todo tipos de jugetes de la mejor calidad, todo en lana y telas",
"2011-08-25",
"Puntadas",
50000.00,
true,
"2019-08-14",
"emprendimientos/crochet",
13);

INSERT INTO `javainfo`.`emprendimiento`
(`id`,
`activo`,
`contador_de_votos`,
`contenido`,
`descripcion`,
`fecha_de_creacion`,
`nombre`,
`objetivo`,
`publicado`,
`ultima_modificacion`,
`url`,
`jefe_id`)
VALUES
(6,
true,
7,
"Articulos Rurales",
"Los mejores accesorios para un día de campo",
"2005-11-12",
"AgroRural",
50000.00,
true,
"2019-08-14",
"emprendimientos/ruralisimo",
11);

INSERT INTO `javainfo`.`emprendimiento`
(`id`,
`activo`,
`contador_de_votos`,
`contenido`,
`descripcion`,
`fecha_de_creacion`,
`nombre`,
`objetivo`,
`publicado`,
`ultima_modificacion`,
`url`,
`jefe_id`)
VALUES
(8,
true,
0,
"Deporte",
"Las mejores bendas y de la mejor calidad",
"1998-12-15",
"Valvet",
50000.00,
true,
"2009-09-14",
"emprendimientos/valvet",
6);

INSERT INTO `javainfo`.`emprendimiento`
(`id`,
`activo`,
`contador_de_votos`,
`contenido`,
`descripcion`,
`fecha_de_creacion`,
`nombre`,
`objetivo`,
`publicado`,
`ultima_modificacion`,
`url`,
`jefe_id`)
VALUES
(9,
true,
15,
"Tecnologia",
"Articulos para adornar todo los modelos de celulares",
"2017-10-01",
"TecnoCell",
50000.00,
true,
"2019-08-14",
"emprendimientos/tecnocell",
1);
